---
- name: Testing andrewrothstein.packer
  hosts: all
  tasks:
    - name: Installing andrewrothstein.packer
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'packer --version'
      ansible.builtin.command: /usr/local/bin/packer --version
      changed_when: false
      register: packer_test_output
    - name: Output of 'packer --version'
      ansible.builtin.debug:
        msg: '{{ packer_test_output.stdout }}'
